/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import javax.swing.*;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
/**
 *
 * @author VALENTINA
 */
public class Lista_Materias extends javax.swing.JFrame {

    /**
     * Creates new form Lista_Materias
     */
 public Lista_Materias() {
        initComponents();
        mostrarMaterias();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_ListaMaterias = new javax.swing.JLabel();
        Scroll_listadoMa = new javax.swing.JScrollPane();
        textAreaMaterias = new javax.swing.JTextArea();
        LabelIndicaciones = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TextID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        ImagenVentana1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_ListaMaterias.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Label_ListaMaterias.setForeground(new java.awt.Color(255, 255, 255));
        Label_ListaMaterias.setText("LISTA DE MATERAS");
        getContentPane().add(Label_ListaMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        textAreaMaterias.setColumns(20);
        textAreaMaterias.setRows(5);
        Scroll_listadoMa.setViewportView(textAreaMaterias);

        getContentPane().add(Scroll_listadoMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 330, 140));

        LabelIndicaciones.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelIndicaciones.setText("Escriba el ID de la materia que desea incribir");
        getContentPane().add(LabelIndicaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 222, 157));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 310, 20));

        TextID.setBackground(new java.awt.Color(255, 222, 157));
        getContentPane().add(TextID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 70, -1));

        jButton1.setBackground(new java.awt.Color(153, 255, 102));
        jButton1.setText("Añadir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        ImagenVentana1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagen_Ventana1.jpg"))); // NOI18N
        ImagenVentana1.setText("LISTA MATERIAS");
        ImagenVentana1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(ImagenVentana1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 410, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String nombre;
   int creditos;
    int cupoMaximo;
   String horario;
   int materiasMatriculadas;
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void mostrarMaterias() {
        String rutaArchivo = "datos_materias.txt";
        mostrarArchivo(rutaArchivo);
    }

    public void mostrarArchivo(String rutaArchivo) {
        try (BufferedReader bufferedReader = new BufferedReader(new FileReader(rutaArchivo))) {
            String linea;
            while ((linea = bufferedReader.readLine()) != null) {
                textAreaMaterias.append(linea + "\n");
            }
        } catch (IOException e) {
            textAreaMaterias.append("Error al leer el archivo: " + e.getMessage() + "\n");
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lista_Materias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lista_Materias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lista_Materias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lista_Materias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lista_Materias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagenVentana1;
    private javax.swing.JLabel LabelIndicaciones;
    private javax.swing.JLabel Label_ListaMaterias;
    private javax.swing.JScrollPane Scroll_listadoMa;
    private javax.swing.JTextField TextID;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea textAreaMaterias;
    // End of variables declaration//GEN-END:variables
}
