/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import inscribir_materias.Lista_Materias;
import inscribir_materias.Estudiante;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
/**
 *
 * @author VALENTINA
 */
public class Ventana1 extends javax.swing.JFrame {

    /**
     * Creates new form Lista_materia
     */
    public Ventana1() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelMatricula = new javax.swing.JLabel();
        LabelCodigo = new javax.swing.JLabel();
        Labelnombre_Estudiante = new javax.swing.JLabel();
        TextCodigo = new javax.swing.JTextField();
        TextNombre_Estudiante = new javax.swing.JTextField();
        BotonInscribir = new javax.swing.JButton();
        ImagenVentana1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelMatricula.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabelMatricula.setForeground(new java.awt.Color(255, 255, 255));
        LabelMatricula.setText("BIENVENIDO!");
        getContentPane().add(LabelMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        LabelCodigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelCodigo.setForeground(new java.awt.Color(255, 255, 255));
        LabelCodigo.setText("Codigo:");
        getContentPane().add(LabelCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        Labelnombre_Estudiante.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Labelnombre_Estudiante.setForeground(new java.awt.Color(255, 255, 255));
        Labelnombre_Estudiante.setText("Nombre:");
        getContentPane().add(Labelnombre_Estudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));
        getContentPane().add(TextCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 90, -1));
        getContentPane().add(TextNombre_Estudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 110, -1));

        BotonInscribir.setBackground(new java.awt.Color(102, 102, 0));
        BotonInscribir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BotonInscribir.setText("Inscribir Materias");
        BotonInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInscribirActionPerformed(evt);
            }
        });
        getContentPane().add(BotonInscribir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 140, -1));

        ImagenVentana1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagen_Ventana1.jpg"))); // NOI18N
        ImagenVentana1.setText("BIENVENIDO");
        getContentPane().add(ImagenVentana1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 410, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInscribirActionPerformed
        
        try {
            // Obtener el código y el nombre del estudiante
            String codigo = TextCodigo.getText();
            String nombre = TextNombre_Estudiante.getText();

            // Verificar que el código sea un número
            int codigoInt = Integer.parseInt(codigo);

            // Si el código es un número, crear una instancia de Estudiante
            Estudiante estudiante = new Estudiante(codigo, nombre, 18);

            // Asignar valores a las variables globales en Lista_Materias
            Lista_Materias.nombreEstudiante = nombre;
            Lista_Materias.codigoEstudiante = codigo;

            // Abrir la ventana de lista de materias
            Lista_Materias listaMaterias = new Lista_Materias();
            // Pasar el estudiante a la lista de materias
            listaMaterias.setVisible(true);
            // Cerrar la ventana actual
            dispose();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un número válido", "Error de entrada", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException e) {
            // Capturar la excepción si el nombre está vacío
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un nombre válido.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_BotonInscribirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonInscribir;
    private javax.swing.JLabel ImagenVentana1;
    private javax.swing.JLabel LabelCodigo;
    private javax.swing.JLabel LabelMatricula;
    private javax.swing.JLabel Labelnombre_Estudiante;
    private javax.swing.JTextField TextCodigo;
    private javax.swing.JTextField TextNombre_Estudiante;
    // End of variables declaration//GEN-END:variables
}
